name: mastodon_generator
publish_to: none
environment:
  sdk: ^3.6.0
resolution: workspace
dependencies:
  openapi_generator_annotations: ^6.1.0
dev_dependencies:
  openapi_generator: ^6.1.0
  build_runner: ^2.5.4
