name: mastodon_generator
publish_to: none
environment:
  sdk: ^3.9.0
resolution: workspace
dependencies:
  openapi_generator_annotations: any
dev_dependencies:
  openapi_generator: any
  build_runner: any
