#!/bin/bash
set -e

cd packages/mastodon_generator

dart run build_runner build --delete-conflicting-outputs

cd ../..

dart format .

dart packages/mastodon_generator/lib/hacks.dart

cd packages/mastodon

dart run build_runner build --delete-conflicting-outputs

dart fix --apply --code=unused_import

cd ../..

dart format .
